MainScreen:

<MainScreen>:
    BoxLayout:
        orientation: "vertical"
        size: root.size
        BoxLayout:
            Label:
                id: label1
                text: "English word"
            TextInput:
                id: textinput1
        BoxLayout:
            Label:
                id: label2
                text: "Trasrated"
            TextInput:
                id: textinput2